# Generated by Django 4.0.1 on 2022-01-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menteeRowInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('numLeetCode', models.IntegerField()),
                ('jobRole', models.CharField(max_length=20)),
                ('linkedLink', models.URLField()),
                ('leetcodeLink', models.URLField()),
                ('skills', models.CharField(max_length=500)),
                ('projects', models.CharField(max_length=500)),
                ('jobId', models.CharField(max_length=20)),
                ('jobDescriptionLink', models.URLField()),
            ],
        ),
    ]
